baseURL = 'http://L-Gregory.github.io/'
title = "Hi, I'm Luke!"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10
publishDir = "docs"

[permalinks]
 posts = "/posts/:year/:month/:title/"

[author]
 name = "Luke Gregory"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "A Postdoctoral Associate at Cornell University"
  backgroundImage = "/img/Background3.png"

  # Theme color and toggle
  enableThemeToggle = false
  color_theme = "light"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "Luke Gregory"
  keywords = "homepage"
  images = [""]

[params.portrait]
  path     = "/img/Headshot_2022.jpg"
  alt      = "Portrait"
  maxWidth = "300px"



 # Social icons 
 [[params.social]]
    name = "twitter"
    url = "https://twitter.com/LukeMGregory"

 [[params.social]]
    name = "googlescholar"
    url = "https://scholar.google.com/citations?user=6PxF2p0AAAAJ&hl=en&oi=ao"

  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/luke-gregory-b74152134/"

  [[params.social]]
    name = "github"
    url = "https://github.com/L-Gregory"


[params.footer]
    topText = []
    bottomText = [
      "Updated: Summer 2024"
    ]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    subtitle = "An Academic Portfolio"
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

  [languages.en.params.logo]
      logoMark = " " # marker in front of logoText 
      logoText = "Home" # title text at top screen
      logoHomeLink = "/" # Link back to home page
      #logoCursorDisabled = true # Remove cursor flash
      logoCursorColor = "#2E4D4D" # Change HEX color for cursor 

# And you can even create generic menu
[menu]
  [[menu.main]]
      identifier = "aboutme"
      name       = "About Me"
      url        = "/aboutme/"

  [[menu.main]]
      identifier = "projects"
      name       = "Projects"
      url        = "/projects/"

    [[menu.main]]
      identifier = "teaching"
      name       = "Teaching"
      url        = "/teaching/"

  [[menu.main]]
      identifier = "cv"
      name       = "CV"
      url        = "/cv/"

  # [[menu.main]]
     # identifier = "posts"
     # name       = "Blog"
     #  url        = "/posts"






      


